name: traderwho
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.2

# Application dependenciesform_validator
dependencies:
 
  # Utility for consistent spacing between widgets
  gap: ^3.0.1
  # Internationalization and localization support
  intl: ^0.19.0
  # Service locator for dependency injection
  get_it: ^8.0.3
  # Simplifies equality comparisons
  equatable: ^2.0.7
  
  flutter_svg: ^2.1.0
  # Form validation utilities
  form_validator: ^2.1.1
  # Firebase Performance monitoring with Dio integration
  firebase_performance_dio: ^0.7.1
  # Default iOS icons
  cupertino_icons: ^1.0.8
  # Fetch app metadata like version and build number
  package_info_plus: ^8.3.0
  # Firebase push notifications
  firebase_messaging: ^15.2.5
  # Permission handling for various platforms
  permission_handler: ^12.0.0+1
  # File selector for various platforms
  file_selector: ^1.0.3
  # Firebase Analytics for tracking events
  firebase_analytics: ^11.4.5
  # Firebase Crashlytics for error reporting
  firebase_crashlytics: ^4.3.5
  # Pull-to-refresh widget
  liquid_pull_to_refresh: ^3.0.1
  # Network connection checker
  simple_connection_checker: ^0.3.4


  # Navigation and routing library
  go_router: ^15.1.1
  # Logging utility
  logger: ^2.5.0
  # Functional programming utilities
  dartz: ^0.10.1
  # Path manipulation library
  path: ^1.9.1
  # Manages nested state dependencies
  nested: ^1.0.0
  # Table Calendar
  table_calendar: ^3.1.3
  # Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Image Picker
  image_picker: ^1.1.2
  #Image picker for web
  image_picker_for_web: ^3.0.6
  # Infinite Scroll Pagination
  infinite_scroll_pagination: ^5.0.0
  
 
  # Cached Network Image
  cached_network_image: ^3.4.1



  # Flutter SDK dependency
  flutter:
    sdk: flutter

  # Enables localization support in Flutter
  flutter_localizations:
    sdk: flutter
  lottie: ^3.3.1
  file_picker: ^10.1.5
 
  google_fonts: ^6.2.1
  get: ^4.7.2
  google_maps_flutter: ^2.12.2
  flutter_rating_bar: ^4.0.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  shimmer_animation: ^2.2.2
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  firebase_storage: ^12.4.8
 

# Developer-specific dependencies for testing and tooling
dev_dependencies:

  
  # Generates launcher icons for the application
  flutter_launcher_icons: ^0.14.3
  # Recommended lint rules for Flutter
  flutter_lints: ^5.0.0

  # Testing framework for Flutter
  flutter_test:
    sdk: flutter

# Flutter-specific settings
flutter:
  # Use Material Design icons
  uses-material-design: true
  # Enable code generation
  generate: true

  # List of assets used in the project
  assets:
    - assets/images/
    - assets/svgs/
    - assets/fonts/
  # Using Google Fonts instead of local font files
        
         

# Configuration for asset management and code generation (if applicable)
flutter_assets:
  assets_path:
    - assets/images/
    - assets/svgs/
    
  output_path: lib/core/theme
  filename: assets.dart
  field_prefix:
    from: assets
    to:
