import 'package:firebase_auth/firebase_auth.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:traderou/core/shared_widgets/custom_sccfold.dart';
import 'package:traderou/controller/booking_controller.dart';
import 'package:traderou/controller/chat_controller.dart';
import 'package:traderou/core/shared_widgets/custom_nav_bar.dart';
import 'package:traderou/core/shared_widgets/custom_sccfold.dart';
import 'package:traderou/core/shared_widgets/format_current_time.dart';
import 'package:traderou/core/shared_widgets/search_bar_tile.dart';
import 'package:traderou/core/theme/app_color.dart';
import 'package:traderou/core/theme/assets.dart';
import 'package:traderou/models/chat_model.dart';
import 'package:traderou/models/models.dart';
import 'package:traderou/views/chat/presentation/widgets/widgets.dart';

part 'chat_detail_page.dart';
part 'chat_page.dart';
