// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd-TO-5zTRwB5wbgOfSYRw8lJsPBGEO84',
    appId: '1:371566690832:web:702d5b6889c9841ab34095',
    messagingSenderId: '371566690832',
    projectId: 'traderwho-7a1f9',
    authDomain: 'traderwho-7a1f9.firebaseapp.com',
    storageBucket: 'traderwho-7a1f9.firebasestorage.app',
    measurementId: 'G-YWW94323VM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArhr-ZW_JFutiFAMzoSzVNnZv6w9S-x3o',
    appId: '1:371566690832:android:cb115f9069295fe3b34095',
    messagingSenderId: '371566690832',
    projectId: 'traderwho-7a1f9',
    storageBucket: 'traderwho-7a1f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCazHDQ9aKArx70hJkcG5FCS9x1ZiRgY9E',
    appId: '1:371566690832:ios:b037b7d58cf45f3db34095',
    messagingSenderId: '371566690832',
    projectId: 'traderwho-7a1f9',
    storageBucket: 'traderwho-7a1f9.firebasestorage.app',
    iosBundleId: 'com.example.traderwho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCazHDQ9aKArx70hJkcG5FCS9x1ZiRgY9E',
    appId: '1:371566690832:ios:b037b7d58cf45f3db34095',
    messagingSenderId: '371566690832',
    projectId: 'traderwho-7a1f9',
    storageBucket: 'traderwho-7a1f9.firebasestorage.app',
    iosBundleId: 'com.example.traderwho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd-TO-5zTRwB5wbgOfSYRw8lJsPBGEO84',
    appId: '1:371566690832:web:18764bd2d4dc5b17b34095',
    messagingSenderId: '371566690832',
    projectId: 'traderwho-7a1f9',
    authDomain: 'traderwho-7a1f9.firebaseapp.com',
    storageBucket: 'traderwho-7a1f9.firebasestorage.app',
    measurementId: 'G-LQP4FR4CTN',
  );
}
