import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:flutter_svg/svg.dart';
import 'package:get/get.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:traderou/controller/job_history_page_controller.dart';
import 'package:traderou/controller/trade_job_history_controller.dart';
import 'package:traderou/core/shared_widgets/custom_button.dart';
import 'package:traderou/core/shared_widgets/custom_circle_avatar.dart';
import 'package:traderou/core/shared_widgets/custom_sccfold.dart';
import 'package:traderou/core/shared_widgets/custom_text.dart';
import 'package:traderou/core/shared_widgets/custom_textfield.dart';
import 'package:traderou/core/shared_widgets/custom_toggle_button.dart';
import 'package:traderou/core/theme/app_color.dart';
import 'package:traderou/core/theme/assets.dart';
import 'package:traderou/core/theme/constant.dart';
import 'package:traderou/models/models.dart';
import 'package:traderou/models/user_model.dart';
import 'package:traderou/views/trades_job_history/presentation/pages/pages.dart';
import 'package:traderou/views/trades_people/presentation/widgets/widgets.dart';

// part 'custom_map_bottom_sheet.dart';
// part 'map_bottom_sheet_helper.dart';
part 'customer_card.dart';
part 'trade_job_history_bottom_sheet.dart';
part 'trade_job_history_container.dart';
part 'trade_job_history_detail_appbar.dart';
part 'trade_job_history_map_screen.dart';
part 'trades_job_history_appbar.dart';
